In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv('patientID_HPV_status.csv')

In [4]:
df['PATIENT_ID'] = df['PATIENT_ID'].apply(lambda x:x+'-01')

In [9]:
to_use = list(df[df['SUBTYPE']=='HNSC_HPV-']['PATIENT_ID'])

In [11]:
len(set(to_use))

415

In [12]:
df2 = pd.read_csv('metabolic_genes.1570.sCNV.TCGA.csv')

In [15]:
df2[df2['PatientID'].isin(to_use)].set_index('PatientID').to_csv('metabolic_genes.1570.sCNV.TCGA.hpvN.csv')

In [16]:
df3 = pd.read_csv('survival.data.509.TCGA.csv')

In [19]:
df3[df3['PatientID'].isin(to_use)].set_index('PatientID').to_csv('survival.data.509.TCGA.hpvN.csv')

           PatientID  Overall Survival Status  Overall Survival (Months)
0    TCGA-CV-7414-01                      1.0                   0.460269
1    TCGA-CV-6943-01                      1.0                  19.791564
2    TCGA-BA-A8YP-01                      0.0                  16.405300
3    TCGA-CV-5977-01                      0.0                  60.492488
4    TCGA-CV-A6JO-01                      1.0                   6.476641
..               ...                      ...                        ...
503  TCGA-CN-A641-01                      0.0                  12.065621
504  TCGA-P3-A6T5-01                      1.0                  28.996942
505  TCGA-C9-A480-01                      0.0                  12.690272
506  TCGA-QK-A6II-01                      1.0                   9.336884
507  TCGA-CV-7410-01                      1.0                 210.967551

[415 rows x 3 columns]

In [20]:
df4 = pd.read_csv('survival.data.102.CPTAC.csv')

In [24]:
pd.concat([df3[df3['PatientID'].isin(to_use)],df4]).set_index('PatientID').to_csv('survival.data.517.TCGA.CPTAC.hpvN.csv')

In [25]:
df5 = pd.read_csv('metabolic_genes.1570.sCNV.CPTAC.csv')

In [29]:
pd.concat([df2[df2['PatientID'].isin(to_use)],df5]).set_index('PatientID').to_csv('metabolic_genes.1570.sCNV.TCGA.CPTAC.hpvN.csv')

,PatientID,A3GALT2,A4GALT,AACS,AADAT,AANAT,AASDHPPT,AASS,ABAT,ABHD14A-ACY1,...,VKORC1,VKORC1L1,VNN1,VNN2,XDH,XXYLT1,XYLB,XYLT1,XYLT2,ZMPSTE24
0,C3N-02695,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1,C3N-04280,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,C3N-02714,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,C3N-04273,-1,-1,0,-1,1,0,0,-1,-1,...,-1,0,0,0,0,1,-1,-1,1,-1
4,C3N-00519,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,C3L-04849,0,0,-1,0,0,-1,-1,0,-1,...,0,1,-1,-1,0,1,-1,0,0,0
98,C3N-01338,0,0,0,0,0,-1,1,0,-1,...,0,0,0,0,0,1,-1,0,1,0
99,C3N-01858,0,0,0,0,0,0,0,0,-1,...,0,0,0,0,0,0,-1,0,0,0
100,C3N-03009,-1,0,0,0,1,0,0,0,-1,...,0,0,0,0,1,1,-1,0,1,-1
101,C3N-00299,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [32]:
to_scale = df2[df2['PatientID'].isin(to_use)]

In [36]:
to_scale.set_index('PatientID',inplace=True)

In [10]:
scaler = MinMaxScaler(feature_range=(0, 1))
# scaled_data = scaler.fit_transform(to_scale.to_numpy())

In [38]:
# Create a new DataFrame with the scaled data, keeping the original column names
scaled_df = pd.DataFrame(scaled_data, columns=to_scale.columns,index=to_scale.index)

In [41]:
scaled_df.to_csv('metabolic_genes.1570.sCNV.TCGA.hpvN.scaled.csv')

In [50]:
df6 = pd.read_csv('metabolic_genes.1570.sCNV.CPTAC.csv')

In [51]:
df6

,PatientID,A3GALT2,A4GALT,AACS,AADAT,AANAT,AASDHPPT,AASS,ABAT,ABHD14A-ACY1,...,VKORC1,VKORC1L1,VNN1,VNN2,XDH,XXYLT1,XYLB,XYLT1,XYLT2,ZMPSTE24
0,C3N-02695,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1,C3N-04280,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,C3N-02714,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,C3N-04273,-1,-1,0,-1,1,0,0,-1,-1,...,-1,0,0,0,0,1,-1,-1,1,-1
4,C3N-00519,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,C3L-04849,0,0,-1,0,0,-1,-1,0,-1,...,0,1,-1,-1,0,1,-1,0,0,0
98,C3N-01338,0,0,0,0,0,-1,1,0,-1,...,0,0,0,0,0,1,-1,0,1,0
99,C3N-01858,0,0,0,0,0,0,0,0,-1,...,0,0,0,0,0,0,-1,0,0,0
100,C3N-03009,-1,0,0,0,1,0,0,0,-1,...,0,0,0,0,1,1,-1,0,1,-1
101,C3N-00299,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [52]:
to_scale = df6

In [53]:
to_scale.set_index('PatientID',inplace=True)

In [54]:
to_scale

,A3GALT2,A4GALT,AACS,AADAT,AANAT,AASDHPPT,AASS,ABAT,ABHD14A-ACY1,ABO,...,VKORC1,VKORC1L1,VNN1,VNN2,XDH,XXYLT1,XYLB,XYLT1,XYLT2,ZMPSTE24
PatientID,,,,,,,,,,,,,,,,,,,,,
C3N-02695,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,1,0,0
C3N-04280,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C3N-02714,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C3N-04273,-1,-1,0,-1,1,0,0,-1,-1,1,...,-1,0,0,0,0,1,-1,-1,1,-1
C3N-00519,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C3L-04849,0,0,-1,0,0,-1,-1,0,-1,0,...,0,1,-1,-1,0,1,-1,0,0,0
C3N-01338,0,0,0,0,0,-1,1,0,-1,0,...,0,0,0,0,0,1,-1,0,1,0
C3N-01858,0,0,0,0,0,0,0,0,-1,0,...,0,0,0,0,0,0,-1,0,0,0
C3N-03009,-1,0,0,0,1,0,0,0,-1,0,...,0,0,0,0,1,1,-1,0,1,-1
C3N-00299,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [55]:
# scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(to_scale.to_numpy())

In [56]:
# Create a new DataFrame with the scaled data, keeping the original column names
scaled_df = pd.DataFrame(scaled_data, columns=to_scale.columns,index=to_scale.index)

In [57]:
scaled_df.to_csv('metabolic_genes.1570.sCNV.CPTAC.hpvN.scaled.csv')

In [2]:
df8 = pd.read_csv('tcga_cna_common_g.hpvN.csv')

In [4]:
df8.set_index('PatientID',inplace=True)

In [5]:
to_scale = df8

In [11]:
# scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(to_scale.to_numpy())
# Create a new DataFrame with the scaled data, keeping the original column names
scaled_df = pd.DataFrame(scaled_data, columns=to_scale.columns,index=to_scale.index)

In [12]:
scaled_df

,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2MP1,A3GALT2,A4GALT,A4GNT,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
PatientID,,,,,,,,,,,,,,,,,,,,,
TCGA-CV-7414-01,0.333333,0.333333,0.25,0.50,0.50,0.50,0.50,0.333333,0.333333,0.666667,...,0.5,0.000000,0.50,0.50,0.666667,0.0,0.0,0.25,1.000000,0.0
TCGA-CV-6943-01,0.333333,0.333333,0.50,0.50,0.50,0.50,0.50,0.333333,0.333333,0.333333,...,0.5,0.333333,0.50,0.50,0.333333,0.5,0.5,0.50,0.666667,0.5
TCGA-BA-A8YP-01,0.333333,0.333333,0.25,0.75,0.75,0.75,0.75,0.333333,0.333333,0.666667,...,0.0,0.000000,0.75,0.75,0.666667,0.5,0.5,0.25,1.000000,0.5
TCGA-CV-5977-01,0.666667,0.666667,0.25,0.50,0.50,0.50,0.50,0.666667,0.000000,0.666667,...,0.0,0.000000,0.75,0.75,0.666667,1.0,1.0,0.50,1.000000,1.0
TCGA-CV-A6JO-01,0.333333,0.333333,0.50,0.50,0.50,0.50,0.50,0.333333,0.333333,0.333333,...,0.5,0.333333,0.50,0.50,0.333333,0.5,0.5,0.50,0.666667,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-CN-A641-01,0.000000,0.000000,0.50,0.50,0.50,0.50,0.50,0.333333,0.333333,0.333333,...,0.0,0.333333,0.50,0.50,0.333333,0.5,0.5,0.75,0.333333,0.5
TCGA-P3-A6T5-01,0.333333,0.333333,0.25,0.25,0.25,0.25,0.25,0.666667,0.666667,0.666667,...,0.0,0.000000,0.50,0.50,0.666667,1.0,1.0,0.50,0.666667,0.0
TCGA-C9-A480-01,0.333333,0.333333,0.50,0.50,0.50,0.50,0.50,0.333333,0.000000,0.333333,...,0.5,0.333333,0.50,0.50,0.333333,0.5,0.5,0.50,0.666667,0.5
TCGA-QK-A6II-01,0.333333,0.333333,0.50,0.50,0.50,0.50,0.50,0.333333,0.333333,0.333333,...,0.5,0.333333,0.50,0.50,0.333333,0.5,0.5,0.50,0.666667,0.5
TCGA-CV-7410-01,0.333333,0.333333,0.50,0.50,0.50,0.50,0.50,0.333333,0.333333,1.000000,...,0.5,0.333333,0.50,0.50,1.000000,0.5,0.5,0.50,0.666667,0.5

In [13]:
scaled_df.to_csv('common_genes.23037.sCNV.TCGA.hpvN.scaled.csv')

In [15]:
df9 = pd.read_csv('cptac_cna_common_g.csv')

In [19]:
df9.rename(columns={'Unnamed: 0':'PatientID'},inplace=True)

In [20]:
df9.set_index('PatientID',inplace=True)

In [22]:
to_scale = df9

In [23]:
# scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(to_scale.to_numpy())
# Create a new DataFrame with the scaled data, keeping the original column names
scaled_df = pd.DataFrame(scaled_data, columns=to_scale.columns,index=to_scale.index)

In [24]:
scaled_df.to_csv('common_genes.23037.sCNV.CPTAC.hpvN.scaled.csv')